package constant

// Country struct
type Country struct {
	ID     int
	Code   string
	Name   string
	Region int
}

var (
	// Countries config of countries
	Countries = []Country{
		{ID: 1, Code: "AF", Name: "Afghanistan", Region: 2},
		{ID: 2, Code: "AX", Name: "Åland Islands", Region: 3},
		{ID: 3, Code: "AL", Name: "Albania", Region: 3},
		{ID: 4, Code: "DZ", Name: "Algeria", Region: 1},
		{ID: 5, Code: "AS", Name: "American Samoa", Region: 6},
		{ID: 6, Code: "AD", Name: "Andorra", Region: 3},
		{ID: 7, Code: "AO", Name: "Angola", Region: 1},
		{ID: 8, Code: "AI", Name: "Anguilla", Region: 4},
		{ID: 9, Code: "AQ", Name: "Antarctica", Region: 6},
		{ID: 10, Code: "AG", Name: "Antigua and Barbuda", Region: 4},
		{ID: 11, Code: "AR", Name: "Argentina", Region: 4},
		{ID: 12, Code: "AM", Name: "Armenia", Region: 2},
		{ID: 13, Code: "AW", Name: "Aruba", Region: 4},
		{ID: 14, Code: "AU", Name: "Australia", Region: 6},
		{ID: 15, Code: "AT", Name: "Austria", Region: 3},
		{ID: 16, Code: "AZ", Name: "Azerbaijan", Region: 2},
		{ID: 17, Code: "BS", Name: "Bahamas", Region: 4},
		{ID: 18, Code: "BH", Name: "Bahrain", Region: 2},
		{ID: 19, Code: "BD", Name: "Bangladesh", Region: 2},
		{ID: 20, Code: "BB", Name: "Barbados", Region: 4},
		{ID: 21, Code: "BY", Name: "Belarus", Region: 3},
		{ID: 22, Code: "BE", Name: "Belgium", Region: 3},
		{ID: 23, Code: "BZ", Name: "Belize", Region: 4},
		{ID: 24, Code: "BJ", Name: "Benin", Region: 1},
		{ID: 25, Code: "BM", Name: "Bermuda", Region: 4},
		{ID: 26, Code: "BT", Name: "Bhutan", Region: 2},
		{ID: 27, Code: "BO", Name: "Bolivia, Plurinational State of", Region: 4},
		{ID: 28, Code: "BQ", Name: "Bonaire, Sint Eustatius and Saba", Region: 4},
		{ID: 29, Code: "BA", Name: "Bosnia and Herzegovina", Region: 3},
		{ID: 30, Code: "BW", Name: "Botswana", Region: 1},
		{ID: 31, Code: "BV", Name: "Bouvet Island", Region: 3},
		{ID: 32, Code: "BR", Name: "Brazil", Region: 4},
		{ID: 33, Code: "IO", Name: "British Indian Ocean Territory", Region: 2},
		{ID: 34, Code: "BN", Name: "Brunei Darussalam", Region: 2},
		{ID: 35, Code: "BG", Name: "Bulgaria", Region: 3},
		{ID: 36, Code: "BF", Name: "Burkina Faso", Region: 1},
		{ID: 37, Code: "BI", Name: "Burundi", Region: 1},
		{ID: 38, Code: "KH", Name: "Cambodia", Region: 2},
		{ID: 39, Code: "CM", Name: "Cameroon", Region: 1},
		{ID: 40, Code: "CA", Name: "Canada", Region: 5},
		{ID: 41, Code: "CV", Name: "Cape Verde", Region: 1},
		{ID: 42, Code: "KY", Name: "Cayman Islands", Region: 4},
		{ID: 43, Code: "CF", Name: "Central African Republic", Region: 1},
		{ID: 44, Code: "TD", Name: "Chad", Region: 1},
		{ID: 45, Code: "CL", Name: "Chile", Region: 4},
		{ID: 46, Code: "CN", Name: "China", Region: 2},
		{ID: 47, Code: "CX", Name: "Christmas Island", Region: 2},
		{ID: 48, Code: "CC", Name: "Cocos (Keeling) Islands", Region: 2},
		{ID: 49, Code: "CO", Name: "Colombia", Region: 4},
		{ID: 50, Code: "KM", Name: "Comoros", Region: 1},
		{ID: 51, Code: "CG", Name: "Congo", Region: 1},
		{ID: 52, Code: "CD", Name: "Congo, the Democratic Republic of the", Region: 1},
		{ID: 53, Code: "CK", Name: "Cook Islands", Region: 6},
		{ID: 54, Code: "CR", Name: "Costa Rica", Region: 4},
		{ID: 55, Code: "CI", Name: "Côte d\"Ivoire", Region: 1},
		{ID: 56, Code: "HR", Name: "Croatia", Region: 3},
		{ID: 57, Code: "CU", Name: "Cuba", Region: 4},
		{ID: 58, Code: "CW", Name: "Curaçao", Region: 4},
		{ID: 59, Code: "CY", Name: "Cyprus", Region: 3},
		{ID: 60, Code: "CZ", Name: "Czech Republic", Region: 3},
		{ID: 61, Code: "DK", Name: "Denmark", Region: 3},
		{ID: 62, Code: "DJ", Name: "Djibouti", Region: 1},
		{ID: 63, Code: "DM", Name: "Dominica", Region: 4},
		{ID: 64, Code: "DO", Name: "Dominican Republic", Region: 4},
		{ID: 65, Code: "EC", Name: "Ecuador", Region: 4},
		{ID: 66, Code: "EG", Name: "Egypt", Region: 1},
		{ID: 67, Code: "SV", Name: "El Salvador", Region: 4},
		{ID: 68, Code: "GQ", Name: "Equatorial Guinea", Region: 1},
		{ID: 69, Code: "ER", Name: "Eritrea", Region: 1},
		{ID: 70, Code: "EE", Name: "Estonia", Region: 3},
		{ID: 71, Code: "ET", Name: "Ethiopia", Region: 1},
		{ID: 72, Code: "FK", Name: "Falkland Islands (Malvinas)", Region: 4},
		{ID: 73, Code: "FO", Name: "Faroe Islands", Region: 3},
		{ID: 74, Code: "FJ", Name: "Fiji", Region: 6},
		{ID: 75, Code: "FI", Name: "Finland", Region: 3},
		{ID: 76, Code: "FR", Name: "France", Region: 3},
		{ID: 77, Code: "GF", Name: "French Guiana", Region: 4},
		{ID: 78, Code: "PF", Name: "French Polynesia", Region: 6},
		{ID: 79, Code: "TF", Name: "French Southern Territories", Region: 6},
		{ID: 80, Code: "GA", Name: "Gabon", Region: 1},
		{ID: 81, Code: "GM", Name: "Gambia", Region: 1},
		{ID: 82, Code: "GE", Name: "Georgia", Region: 2},
		{ID: 83, Code: "DE", Name: "Germany", Region: 3},
		{ID: 84, Code: "GH", Name: "Ghana", Region: 1},
		{ID: 85, Code: "GI", Name: "Gibraltar", Region: 3},
		{ID: 86, Code: "GR", Name: "Greece", Region: 3},
		{ID: 87, Code: "GL", Name: "Greenland", Region: 3},
		{ID: 88, Code: "GD", Name: "Grenada", Region: 4},
		{ID: 89, Code: "GP", Name: "Guadeloupe", Region: 4},
		{ID: 90, Code: "GU", Name: "Guam", Region: 6},
		{ID: 91, Code: "GT", Name: "Guatemala", Region: 4},
		{ID: 92, Code: "GG", Name: "Guernsey", Region: 3},
		{ID: 93, Code: "GN", Name: "Guinea", Region: 1},
		{ID: 94, Code: "GW", Name: "Guinea-Bissau", Region: 1},
		{ID: 95, Code: "GY", Name: "Guyana", Region: 4},
		{ID: 96, Code: "HT", Name: "Haiti", Region: 4},
		{ID: 97, Code: "HM", Name: "Heard Island and McDonald Islands", Region: 6},
		{ID: 98, Code: "VA", Name: "Holy See (Vatican City State)", Region: 3},
		{ID: 99, Code: "HN", Name: "Honduras", Region: 4},
		{ID: 100, Code: "HK", Name: "Hong Kong", Region: 2},
		{ID: 101, Code: "HU", Name: "Hungary", Region: 3},
		{ID: 102, Code: "IS", Name: "Iceland", Region: 3},
		{ID: 103, Code: "IN", Name: "India", Region: 2},
		{ID: 104, Code: "ID", Name: "Indonesia", Region: 2},
		{ID: 105, Code: "IR", Name: "Iran, Islamic Republic of", Region: 2},
		{ID: 106, Code: "IQ", Name: "Iraq", Region: 2},
		{ID: 107, Code: "IE", Name: "Ireland", Region: 3},
		{ID: 108, Code: "IM", Name: "Isle of Man", Region: 3},
		{ID: 109, Code: "IL", Name: "Israel", Region: 2},
		{ID: 110, Code: "IT", Name: "Italy", Region: 3},
		{ID: 111, Code: "JM", Name: "Jamaica", Region: 4},
		{ID: 112, Code: "JP", Name: "Japan", Region: 2},
		{ID: 113, Code: "JE", Name: "Jersey", Region: 3},
		{ID: 114, Code: "JO", Name: "Jordan", Region: 2},
		{ID: 115, Code: "KZ", Name: "Kazakhstan", Region: 2},
		{ID: 116, Code: "KE", Name: "Kenya", Region: 1},
		{ID: 117, Code: "KI", Name: "Kiribati", Region: 6},
		{ID: 118, Code: "KP", Name: "Korea, Democratic People\"s Republic of", Region: 2},
		{ID: 119, Code: "KR", Name: "Korea, Republic of", Region: 2},
		{ID: 120, Code: "KW", Name: "Kuwait", Region: 2},
		{ID: 121, Code: "KG", Name: "Kyrgyzstan", Region: 2},
		{ID: 122, Code: "LA", Name: "Lao People\"s Democratic Republic", Region: 2},
		{ID: 123, Code: "LV", Name: "Latvia", Region: 3},
		{ID: 124, Code: "LB", Name: "Lebanon", Region: 2},
		{ID: 125, Code: "LS", Name: "Lesotho", Region: 1},
		{ID: 126, Code: "LR", Name: "Liberia", Region: 1},
		{ID: 127, Code: "LY", Name: "Libya", Region: 1},
		{ID: 128, Code: "LI", Name: "Liechtenstein", Region: 3},
		{ID: 129, Code: "LT", Name: "Lithuania", Region: 3},
		{ID: 130, Code: "LU", Name: "Luxembourg", Region: 3},
		{ID: 131, Code: "MO", Name: "Macao", Region: 2},
		{ID: 132, Code: "MK", Name: "Macedonia, the former Yugoslav Republic of", Region: 3},
		{ID: 133, Code: "MG", Name: "Madagascar", Region: 1},
		{ID: 134, Code: "MW", Name: "Malawi", Region: 1},
		{ID: 135, Code: "MY", Name: "Malaysia", Region: 2},
		{ID: 136, Code: "MV", Name: "Maldives", Region: 2},
		{ID: 137, Code: "ML", Name: "Mali", Region: 1},
		{ID: 138, Code: "MT", Name: "Malta", Region: 3},
		{ID: 139, Code: "MH", Name: "Marshall Islands", Region: 6},
		{ID: 140, Code: "MQ", Name: "Martinique", Region: 4},
		{ID: 141, Code: "MR", Name: "Mauritania", Region: 1},
		{ID: 142, Code: "MU", Name: "Mauritius", Region: 1},
		{ID: 143, Code: "YT", Name: "Mayotte", Region: 1},
		{ID: 144, Code: "MX", Name: "Mexico", Region: 4},
		{ID: 145, Code: "FM", Name: "Micronesia, Federated States of", Region: 6},
		{ID: 146, Code: "MD", Name: "Moldova, Republic of", Region: 3},
		{ID: 147, Code: "MC", Name: "Monaco", Region: 3},
		{ID: 148, Code: "MN", Name: "Mongolia", Region: 2},
		{ID: 149, Code: "ME", Name: "Montenegro", Region: 3},
		{ID: 150, Code: "MS", Name: "Montserrat", Region: 3},
		{ID: 151, Code: "MA", Name: "Morocco", Region: 1},
		{ID: 152, Code: "MZ", Name: "Mozambique", Region: 1},
		{ID: 153, Code: "MM", Name: "Myanmar", Region: 2},
		{ID: 154, Code: "NA", Name: "Namibia", Region: 1},
		{ID: 155, Code: "NR", Name: "Nauru", Region: 6},
		{ID: 156, Code: "NP", Name: "Nepal", Region: 2},
		{ID: 157, Code: "NL", Name: "Netherlands", Region: 3},
		{ID: 158, Code: "NC", Name: "New Caledonia", Region: 6},
		{ID: 159, Code: "NZ", Name: "New Zealand", Region: 6},
		{ID: 160, Code: "NI", Name: "Nicaragua", Region: 4},
		{ID: 161, Code: "NE", Name: "Niger", Region: 1},
		{ID: 162, Code: "NG", Name: "Nigeria", Region: 1},
		{ID: 163, Code: "NU", Name: "Niue", Region: 6},
		{ID: 164, Code: "NF", Name: "Norfolk Island", Region: 6},
		{ID: 165, Code: "MP", Name: "Northern Mariana Islands", Region: 6},
		{ID: 166, Code: "NO", Name: "Norway", Region: 3},
		{ID: 167, Code: "OM", Name: "Oman", Region: 2},
		{ID: 168, Code: "PK", Name: "Pakistan", Region: 2},
		{ID: 169, Code: "PW", Name: "Palau", Region: 6},
		{ID: 170, Code: "PS", Name: "Palestinian Territory, Occupied", Region: 2},
		{ID: 171, Code: "PA", Name: "Panama", Region: 4},
		{ID: 172, Code: "PG", Name: "Papua New Guinea", Region: 6},
		{ID: 173, Code: "PY", Name: "Paraguay", Region: 4},
		{ID: 174, Code: "PE", Name: "Peru", Region: 4},
		{ID: 175, Code: "PH", Name: "Philippines", Region: 2},
		{ID: 176, Code: "PN", Name: "Pitcairn", Region: 6},
		{ID: 177, Code: "PL", Name: "Poland", Region: 3},
		{ID: 178, Code: "PT", Name: "Portugal", Region: 3},
		{ID: 179, Code: "PR", Name: "Puerto Rico", Region: 5},
		{ID: 180, Code: "QA", Name: "Qatar", Region: 2},
		{ID: 181, Code: "RO", Name: "Romania", Region: 3},
		{ID: 182, Code: "RU", Name: "Russian Federation", Region: 3},
		{ID: 183, Code: "RW", Name: "Rwanda", Region: 1},
		{ID: 184, Code: "RE", Name: "Réunion", Region: 1},
		{ID: 185, Code: "BL", Name: "Saint Barthélemy", Region: 4},
		{ID: 186, Code: "SH", Name: "Saint Helena, Ascension and Tristan da Cunha", Region: 4},
		{ID: 187, Code: "KN", Name: "Saint Kitts and Nevis", Region: 4},
		{ID: 188, Code: "LC", Name: "Saint Lucia", Region: 4},
		{ID: 189, Code: "MF", Name: "Saint Martin (French part)", Region: 4},
		{ID: 190, Code: "PM", Name: "Saint Pierre and Miquelon", Region: 5},
		{ID: 191, Code: "VC", Name: "Saint Vincent and the Grenadines", Region: 4},
		{ID: 192, Code: "WS", Name: "Samoa", Region: 6},
		{ID: 193, Code: "SM", Name: "San Marino", Region: 3},
		{ID: 194, Code: "ST", Name: "Sao Tome and Principe", Region: 1},
		{ID: 195, Code: "SA", Name: "Saudi Arabia", Region: 2},
		{ID: 196, Code: "SN", Name: "Senegal", Region: 1},
		{ID: 197, Code: "RS", Name: "Serbia", Region: 3},
		{ID: 198, Code: "SC", Name: "Seychelles", Region: 1},
		{ID: 199, Code: "SL", Name: "Sierra Leone", Region: 1},
		{ID: 200, Code: "SG", Name: "Singapore", Region: 2},
		{ID: 201, Code: "SX", Name: "Sint Maarten (Dutch part)", Region: 4},
		{ID: 202, Code: "SK", Name: "Slovakia", Region: 3},
		{ID: 203, Code: "SI", Name: "Slovenia", Region: 3},
		{ID: 204, Code: "SB", Name: "Solomon Islands", Region: 6},
		{ID: 205, Code: "SO", Name: "Somalia", Region: 1},
		{ID: 206, Code: "ZA", Name: "South Africa", Region: 1},
		{ID: 207, Code: "GS", Name: "South Georgia and the South Sandwich Islands", Region: 4},
		{ID: 208, Code: "SS", Name: "South Sudan", Region: 1},
		{ID: 209, Code: "ES", Name: "Spain", Region: 3},
		{ID: 210, Code: "LK", Name: "Sri Lanka", Region: 2},
		{ID: 211, Code: "SD", Name: "Sudan", Region: 1},
		{ID: 212, Code: "SR", Name: "SuriName", Region: 4},
		{ID: 213, Code: "SJ", Name: "Svalbard and Jan Mayen", Region: 3},
		{ID: 214, Code: "SZ", Name: "Swaziland", Region: 1},
		{ID: 215, Code: "SE", Name: "Sweden", Region: 3},
		{ID: 216, Code: "CH", Name: "Switzerland", Region: 3},
		{ID: 217, Code: "SY", Name: "Syrian Arab Republic", Region: 2},
		{ID: 218, Code: "TW", Name: "Taiwan, Province of China", Region: 2},
		{ID: 219, Code: "TJ", Name: "Tajikistan", Region: 2},
		{ID: 220, Code: "TZ", Name: "Tanzania, United Republic of", Region: 1},
		{ID: 221, Code: "TH", Name: "Thailand", Region: 2},
		{ID: 222, Code: "TL", Name: "Timor-Leste", Region: 6},
		{ID: 223, Code: "TG", Name: "Togo", Region: 1},
		{ID: 224, Code: "TK", Name: "Tokelau", Region: 6},
		{ID: 225, Code: "TO", Name: "Tonga", Region: 6},
		{ID: 226, Code: "TT", Name: "TrinIDad and Tobago", Region: 4},
		{ID: 227, Code: "TN", Name: "Tunisia", Region: 1},
		{ID: 228, Code: "TR", Name: "Turkey", Region: 2},
		{ID: 229, Code: "TM", Name: "Turkmenistan", Region: 2},
		{ID: 230, Code: "TC", Name: "Turks and Caicos Islands", Region: 4},
		{ID: 231, Code: "TV", Name: "Tuvalu", Region: 6},
		{ID: 232, Code: "UG", Name: "Uganda", Region: 1},
		{ID: 233, Code: "UA", Name: "Ukraine", Region: 3},
		{ID: 234, Code: "AE", Name: "United Arab Emirates", Region: 2},
		{ID: 235, Code: "GB", Name: "United Kingdom", Region: 3},
		{ID: 236, Code: "US", Name: "United States of America", Region: 5},
		{ID: 237, Code: "UM", Name: "United States Minor Outlying Islands", Region: 6},
		{ID: 238, Code: "UY", Name: "Uruguay", Region: 4},
		{ID: 239, Code: "UZ", Name: "Uzbekistan", Region: 2},
		{ID: 240, Code: "VU", Name: "Vanuatu", Region: 6},
		{ID: 241, Code: "VE", Name: "Venezuela, Bolivarian Republic of", Region: 4},
		{ID: 242, Code: "VN", Name: "Vietnam", Region: 2},
		{ID: 243, Code: "VG", Name: "Virgin Islands, British", Region: 4},
		{ID: 244, Code: "VI", Name: "Virgin Islands, U.S.", Region: 4},
		{ID: 245, Code: "WF", Name: "Wallis and Futuna", Region: 6},
		{ID: 246, Code: "EH", Name: "Western Sahara", Region: 1},
		{ID: 247, Code: "YE", Name: "Yemen", Region: 2},
		{ID: 248, Code: "ZM", Name: "Zambia", Region: 1},
		{ID: 249, Code: "ZW", Name: "Zimbabwe", Region: 1},
	}

	// CountriesByCode map of countries, code is key
	CountriesByCode = generateCountryMap(Countries)

	// AllCountryCodes country code list
	AllCountryCodes = generateCountryCodes(Countries)
)

// generateCountryMap is used to generate Map
func generateCountryMap(countries []Country) map[string]*Country {
	m := make(map[string]*Country)
	for _, country := range countries {
		c := country
		m[country.Code] = &c
	}
	return m
}

// generateCountryCodes gets country code list of Countries
func generateCountryCodes(countries []Country) []string {
	var codes []string
	for _, country := range countries {
		codes = append(codes, country.Code)
	}
	return codes
}
